"""External service ports — geo, payment, notification, storage."""

from __future__ import annotations

from typing import Protocol


class GeoPort(Protocol):
    async def geocode(self, address: str, city: str | None = None) -> dict: ...
    async def route(
        self,
        from_lng: float,
        from_lat: float,
        to_lng: float,
        to_lat: float,
        mode: str = "walk",
    ) -> dict: ...
    async def distance(self, origins: list[tuple[float, float]], destination: tuple[float, float]) -> list[float]: ...


class PaymentPort(Protocol):
    async def create_payment(self, order_no: str, amount: int) -> dict: ...
    async def query_payment(self, order_no: str) -> dict: ...
    async def refund(self, order_id: str, amount: int, reason: str | None = None) -> dict: ...


class NotificationPort(Protocol):
    async def send_sms(self, phone: str, scene: str) -> bool: ...
    async def verify_sms(self, phone: str, code: str, scene: str) -> bool: ...
    async def send_push(self, user_id: str, title: str, content: str) -> bool: ...


class StoragePort(Protocol):
    async def upload(self, filename: str, content: bytes, content_type: str) -> str: ...
    async def get_url(self, key: str) -> str: ...
    async def delete(self, key: str) -> bool: ...
