"""Repository Protocol ports — dependency inversion boundary.

domain/services depend on these interfaces (not on concrete adapters).
Both backend/adapters/persistence/ and mock_server implement these.
"""

from __future__ import annotations

from datetime import date
from typing import Protocol


class UserRepoPort(Protocol):
    async def get_by_phone(self, phone: str) -> dict | None: ...
    async def get_by_id(self, user_id: str) -> dict | None: ...
    async def create(self, phone: str, password_hash: str, nickname: str) -> dict: ...
    async def update(self, user_id: str, data: dict) -> dict | None: ...


class AdminRepoPort(Protocol):
    async def get_by_username(self, username: str) -> dict | None: ...
    async def get_roles(self, admin_id: str) -> list[dict]: ...


class MerchantRepoPort(Protocol):
    async def list(self, query: dict) -> list[dict]: ...
    async def count(self, query: dict) -> int: ...
    async def get_by_id(self, merchant_id: str) -> dict | None: ...
    async def update_status(self, merchant_id: str, status: str) -> dict | None: ...


class CategoryRepoPort(Protocol):
    async def get_tree(self, type_filter: str | None = None) -> list[dict]: ...
    async def create(self, data: dict) -> dict: ...
    async def update(self, category_id: str, data: dict) -> dict | None: ...
    async def delete(self, category_id: str) -> bool: ...


class ProductRepoPort(Protocol):
    async def list(self, query: dict) -> list[dict]: ...
    async def count(self, query: dict) -> int: ...
    async def get_by_id(self, product_id: str) -> dict | None: ...
    async def create(self, data: dict) -> dict: ...
    async def update(self, product_id: str, data: dict) -> dict | None: ...
    async def update_stock(self, product_id: str, spec_value_id: str | None, delta: int) -> bool: ...


class OrderRepoPort(Protocol):
    async def create(self, data: dict) -> dict: ...
    async def get_by_id(self, order_id: str) -> dict | None: ...
    async def list_by_user(self, user_id: str, query: dict) -> tuple[list[dict], int]: ...
    async def list_all(self, query: dict) -> tuple[list[dict], int]: ...
    async def update_status(self, order_id: str, target_status: str, operator: str, remark: str | None = None) -> dict | None: ...


class CartRepoPort(Protocol):
    async def get_user_cart(self, user_id: str) -> list[dict]: ...
    async def upsert(self, user_id: str, data: dict) -> dict: ...
    async def update_qty(self, item_id: str, qty: int) -> dict | None: ...
    async def remove(self, item_id: str) -> bool: ...
    async def clear(self, user_id: str) -> None: ...


class AddressRepoPort(Protocol):
    async def list_by_user(self, user_id: str) -> list[dict]: ...
    async def create(self, user_id: str, data: dict) -> dict: ...
    async def update(self, address_id: str, data: dict) -> dict | None: ...
    async def delete(self, address_id: str) -> bool: ...
    async def set_default(self, user_id: str, address_id: str) -> None: ...


class FavoriteRepoPort(Protocol):
    async def list_by_user(self, user_id: str, target_type: str | None = None) -> list[dict]: ...
    async def toggle(self, user_id: str, target_type: str, target_id: str) -> bool: ...


class ReviewRepoPort(Protocol):
    async def list_by_product(self, product_id: str, page: int, size: int) -> tuple[list[dict], int]: ...
    async def create(self, user_id: str, data: dict) -> dict: ...
    async def get_stats(self, product_id: str) -> dict: ...


class BannerRepoPort(Protocol):
    async def list_active(self, position: str | None = None) -> list[dict]: ...
    async def create(self, data: dict) -> dict: ...
    async def update(self, banner_id: str, data: dict) -> dict | None: ...
    async def delete(self, banner_id: str) -> bool: ...


class SearchRepoPort(Protocol):
    async def search(self, query: dict) -> tuple[list[dict], int]: ...
    async def get_hot(self) -> list[dict]: ...
    async def get_history(self, user_id: str) -> list[dict]: ...
    async def add_history(self, user_id: str, keyword: str) -> None: ...


class StatisticsRepoPort(Protocol):
    async def get_revenue_stats(self, start: date, end: date) -> list[dict]: ...
    async def get_product_ranking(self, start: date, end: date, limit: int) -> list[dict]: ...
