"""create tables

Revision ID: 7c7974cb12bd
Revises: 36fc7e368593
Create Date: 2026-05-22 21:08:33.092263

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c7974cb12bd"
down_revision: str | Sequence[str] | None = "36fc7e368593"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _table_exists(name: str) -> bool:
    """Check if a table exists in the current database."""
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)
    return name in inspector.get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("llm_usage_logs"):
        op.create_table(
            "llm_usage_logs",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("model_name", sa.String(length=128), nullable=False),
            sa.Column("provider", sa.String(length=64), nullable=False),
            sa.Column("prompt_tokens", sa.Integer(), nullable=False),
            sa.Column("completion_tokens", sa.Integer(), nullable=False),
            sa.Column("latency_ms", sa.Integer(), nullable=False),
            sa.Column("cost_usd", sa.Float(), nullable=False),
            sa.Column("endpoint", sa.String(length=255), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _table_exists("plan_run_events"):
        op.create_table(
            "plan_run_events",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("event_id", sa.String(length=64), nullable=False),
            sa.Column("run_id", sa.String(length=64), nullable=False),
            sa.Column("plan_id", sa.String(length=64), nullable=False),
            sa.Column("node_name", sa.String(length=128), nullable=False),
            sa.Column("event_type", sa.String(length=64), nullable=False),
            sa.Column("payload_json", sa.JSON(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_plan_run_events_event_id"), "plan_run_events", ["event_id"], unique=True)
    op.create_index(op.f("ix_plan_run_events_event_type"), "plan_run_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_plan_run_events_node_name"), "plan_run_events", ["node_name"], unique=False)
    op.create_index(op.f("ix_plan_run_events_plan_id"), "plan_run_events", ["plan_id"], unique=False)
    op.create_index(op.f("ix_plan_run_events_run_id"), "plan_run_events", ["run_id"], unique=False)
    if not _table_exists("plan_runs"):
        op.create_table(
            "plan_runs",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("run_id", sa.String(length=64), nullable=False),
            sa.Column("plan_id", sa.String(length=64), nullable=False),
            sa.Column("thread_id", sa.String(length=64), nullable=False),
            sa.Column("graph_version", sa.String(length=64), nullable=False),
            sa.Column("request_payload", sa.JSON(), nullable=False),
            sa.Column("final_status", sa.String(length=32), nullable=False),
            sa.Column("seed", sa.Integer(), nullable=False),
            sa.Column("debug", sa.Boolean(), nullable=False),
            sa.Column("error_message", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_plan_runs_plan_id"), "plan_runs", ["plan_id"], unique=False)
    op.create_index(op.f("ix_plan_runs_run_id"), "plan_runs", ["run_id"], unique=True)
    op.create_index(op.f("ix_plan_runs_thread_id"), "plan_runs", ["thread_id"], unique=False)
    if not _table_exists("pois"):
        op.create_table(
            "pois",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("lat", sa.Float(), nullable=False),
            sa.Column("lng", sa.Float(), nullable=False),
            sa.Column("category", sa.String(length=64), nullable=False),
            sa.Column("tags", sa.JSON(), nullable=False),
            sa.Column("avg_rating", sa.Float(), nullable=False),
            sa.Column("metadata", sa.JSON(), nullable=False),
            sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
            sa.Column("group_suitability", sa.JSON(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_pois_category"), "pois", ["category"], unique=False)
    if not _table_exists("runtime_checkpoints"):
        op.create_table(
            "runtime_checkpoints",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("plan_id", sa.String(length=64), nullable=False),
            sa.Column("run_id", sa.String(length=64), nullable=False),
            sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("state_json", sa.JSON(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_runtime_checkpoints_plan_id"), "runtime_checkpoints", ["plan_id"], unique=False)
    op.create_index(op.f("ix_runtime_checkpoints_run_id"), "runtime_checkpoints", ["run_id"], unique=False)
    if not _table_exists("users"):
        op.create_table(
            "users",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("email", sa.String(length=320), nullable=False),
            sa.Column("hashed_password", sa.String(length=128), nullable=False),
            sa.Column("oauth_provider", sa.String(length=32), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    if not _table_exists("plans"):
        op.create_table(
            "plans",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("user_id", sa.UUID(), nullable=False),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("status", sa.String(length=32), nullable=False),
            sa.Column("date_range", postgresql.DATERANGE(), nullable=False),
            sa.Column("group_type", sa.String(length=32), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_plans_date_range"), "plans", ["date_range"], unique=False)
    op.create_index(op.f("ix_plans_status"), "plans", ["status"], unique=False)
    op.create_index(op.f("ix_plans_user_id"), "plans", ["user_id"], unique=False)
    if not _table_exists("refresh_tokens"):
        op.create_table(
            "refresh_tokens",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("user_id", sa.UUID(), nullable=False),
            sa.Column("token_hash", sa.String(length=255), nullable=False),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=False)
    if not _table_exists("user_profiles"):
        op.create_table(
            "user_profiles",
            sa.Column("user_id", sa.UUID(), nullable=False),
            sa.Column("nickname", sa.String(length=64), nullable=False),
            sa.Column("avatar_url", sa.String(length=512), nullable=True),
            sa.Column("preferences", sa.JSON(), nullable=False),
            sa.Column("travel_style", sa.String(length=32), nullable=True),
            sa.Column("preference_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
            sa.Column("home_address", sa.JSON(), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("user_id"),
        )
    if not _table_exists("checkpoints"):
        op.create_table(
            "checkpoints",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("plan_id", sa.UUID(), nullable=False),
            sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("slots_snapshot", sa.JSON(), nullable=False),
            sa.Column("consensus_status", sa.String(length=32), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(
                ["plan_id"],
                ["plans.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_checkpoints_plan_id"), "checkpoints", ["plan_id"], unique=False)
    if not _table_exists("plan_adjustments"):
        op.create_table(
            "plan_adjustments",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("plan_id", sa.UUID(), nullable=False),
            sa.Column("trigger_reason", sa.String(length=255), nullable=False),
            sa.Column("original_slots", sa.JSON(), nullable=False),
            sa.Column("adjusted_slots", sa.JSON(), nullable=False),
            sa.Column("user_confirmed", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(
                ["plan_id"],
                ["plans.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _table_exists("plan_slots"):
        op.create_table(
            "plan_slots",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("plan_id", sa.UUID(), nullable=False),
            sa.Column("poi_id", sa.String(length=128), nullable=False),
            sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
            sa.Column("time_end", sa.DateTime(timezone=True), nullable=False),
            sa.Column("slot_status", sa.String(length=32), nullable=False),
            sa.Column("booking_ref", sa.String(length=128), nullable=True),
            sa.Column("buffer_minutes", sa.Integer(), nullable=False),
            sa.Column("actual_end", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(
                ["plan_id"],
                ["plans.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(op.f("ix_plan_slots_plan_id"), "plan_slots", ["plan_id"], unique=False)
    op.create_index(op.f("ix_plan_slots_poi_id"), "plan_slots", ["poi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_slots_poi_id"), table_name="plan_slots")
    op.drop_index(op.f("ix_plan_slots_plan_id"), table_name="plan_slots")
    op.drop_table("plan_slots")
    op.drop_table("plan_adjustments")
    op.drop_index(op.f("ix_checkpoints_plan_id"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_plans_user_id"), table_name="plans")
    op.drop_index(op.f("ix_plans_status"), table_name="plans")
    op.drop_index(op.f("ix_plans_date_range"), table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_runtime_checkpoints_run_id"), table_name="runtime_checkpoints")
    op.drop_index(op.f("ix_runtime_checkpoints_plan_id"), table_name="runtime_checkpoints")
    op.drop_table("runtime_checkpoints")
    op.drop_index(op.f("ix_pois_category"), table_name="pois")
    op.drop_table("pois")
    op.drop_index(op.f("ix_plan_runs_thread_id"), table_name="plan_runs")
    op.drop_index(op.f("ix_plan_runs_run_id"), table_name="plan_runs")
    op.drop_index(op.f("ix_plan_runs_plan_id"), table_name="plan_runs")
    op.drop_table("plan_runs")
    op.drop_index(op.f("ix_plan_run_events_run_id"), table_name="plan_run_events")
    op.drop_index(op.f("ix_plan_run_events_plan_id"), table_name="plan_run_events")
    op.drop_index(op.f("ix_plan_run_events_node_name"), table_name="plan_run_events")
    op.drop_index(op.f("ix_plan_run_events_event_type"), table_name="plan_run_events")
    op.drop_index(op.f("ix_plan_run_events_event_id"), table_name="plan_run_events")
    op.drop_table("plan_run_events")
    op.drop_table("llm_usage_logs")
    # ### end Alembic commands ###
