"""Shared FastAPI dependencies — service injection points.

Both mock_server and backend override these via their own DI setup.
"""

from __future__ import annotations

from typing import Protocol

from fastapi import Depends, Header, HTTPException, Request


class UserServicePort(Protocol):
    """Service interface for user operations."""

    async def register(self, phone: str, password: str, nickname: str) -> dict: ...
    async def login(self, phone: str, password: str) -> dict: ...
    async def get_profile(self, user_id: str) -> dict: ...
    async def update_profile(self, user_id: str, data: dict) -> dict: ...


class MerchantServicePort(Protocol):
    async def list_merchants(self, query: dict) -> tuple[list[dict], int]: ...
    async def get_merchant(self, merchant_id: str) -> dict | None: ...
    async def list_products(self, merchant_id: str, query: dict) -> tuple[list[dict], int]: ...
    async def get_product(self, product_id: str) -> dict | None: ...


class CartServicePort(Protocol):
    async def get_cart(self, user_id: str) -> list[dict]: ...
    async def add_item(self, user_id: str, product_id: str, spec_value_id: str | None, flavor_ids: list[str], qty: int) -> dict: ...
    async def update_qty(self, user_id: str, item_id: str, qty: int) -> dict | None: ...
    async def remove_item(self, user_id: str, item_id: str) -> bool: ...
    async def clear_cart(self, user_id: str) -> None: ...


class OrderServicePort(Protocol):
    async def create_order(self, user_id: str, data: dict) -> dict: ...
    async def get_order(self, order_id: str) -> dict | None: ...
    async def list_orders(self, user_id: str, query: dict) -> tuple[list[dict], int]: ...
    async def cancel_order(self, order_id: str, user_id: str, reason: str | None) -> dict | None: ...
    async def pay_order(self, order_id: str, user_id: str) -> dict | None: ...
    async def update_status(self, order_id: str, target_status: str, operator: str, remark: str | None) -> dict | None: ...


class AddressServicePort(Protocol):
    async def list_addresses(self, user_id: str) -> list[dict]: ...
    async def create_address(self, user_id: str, data: dict) -> dict: ...
    async def update_address(self, user_id: str, address_id: str, data: dict) -> dict | None: ...
    async def delete_address(self, user_id: str, address_id: str) -> bool: ...
    async def set_default(self, user_id: str, address_id: str) -> None: ...


class FavoriteServicePort(Protocol):
    async def list_favorites(self, user_id: str, target_type: str | None) -> list[dict]: ...
    async def toggle(self, user_id: str, target_type: str, target_id: str) -> bool: ...


class SearchServicePort(Protocol):
    async def search(self, query: dict) -> tuple[list[dict], int]: ...
    async def hot_searches(self) -> list[dict]: ...
    async def suggestions(self, q: str) -> list[dict]: ...
    async def history(self, user_id: str) -> list[dict]: ...
    async def clear_history(self, user_id: str) -> None: ...


class ReviewServicePort(Protocol):
    async def create_review(self, user_id: str, data: dict) -> dict: ...
    async def list_reviews(self, product_id: str, page: int, size: int) -> tuple[list[dict], int]: ...
    async def get_stats(self, product_id: str) -> dict: ...


class HomeServicePort(Protocol):
    async def get_banners(self) -> list[dict]: ...
    async def get_categories(self) -> list[dict]: ...
    async def get_recommend(self, lat: float, lng: float, page: int, size: int) -> tuple[list[dict], int]: ...


class AdminServicePort(Protocol):
    async def admin_login(self, username: str, password: str) -> dict: ...
    async def get_dashboard(self) -> dict: ...
    async def list_employees(self, page: int, size: int) -> tuple[list[dict], int]: ...
    async def create_employee(self, data: dict) -> dict: ...
    async def update_employee(self, employee_id: str, data: dict) -> dict | None: ...
    async def delete_employee(self, employee_id: str) -> bool: ...
    async def assign_roles(self, employee_id: str, role_codes: list[str]) -> dict | None: ...
    async def list_roles(self) -> list[dict]: ...
    async def create_role(self, data: dict) -> dict: ...
    async def assign_permissions(self, role_id: str, permission_codes: list[str]) -> dict | None: ...
    async def get_permission_tree(self) -> list[dict]: ...
    async def audit_merchant(self, merchant_id: str, status: str, remark: str | None) -> dict | None: ...
    async def update_merchant_status(self, merchant_id: str, status: str) -> dict | None: ...
    async def get_category_tree(self) -> list[dict]: ...
    async def create_category(self, data: dict) -> dict: ...
    async def update_category(self, category_id: str, data: dict) -> dict | None: ...
    async def delete_category(self, category_id: str) -> bool: ...
    async def list_products_admin(self, query: dict) -> tuple[list[dict], int]: ...
    async def create_product(self, data: dict) -> dict: ...
    async def update_product(self, product_id: str, data: dict) -> dict | None: ...
    async def toggle_product_status(self, product_id: str, status: str) -> dict | None: ...
    async def batch_product_status(self, ids: list[str], status: str) -> None: ...
    async def list_orders_admin(self, query: dict) -> tuple[list[dict], int]: ...
    async def export_orders(self) -> bytes: ...
    async def list_banners(self) -> list[dict]: ...
    async def create_banner(self, data: dict) -> dict: ...
    async def update_banner(self, banner_id: str, data: dict) -> dict | None: ...
    async def delete_banner(self, banner_id: str) -> bool: ...
    async def list_notices(self) -> list[dict]: ...
    async def create_notice(self, data: dict) -> dict: ...
    async def delete_notice(self, notice_id: str) -> bool: ...
    async def upload_image(self, file) -> dict: ...
    async def get_revenue_stats(self, start: str, end: str) -> dict: ...
    async def get_order_stats(self, start: str, end: str) -> dict: ...
    async def get_user_stats(self, start: str, end: str) -> dict: ...
    async def get_product_ranking(self, start: str, end: str, limit: int) -> list[dict]: ...
